<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Marks assessments generated by the Mock Test Builder. Custom tests belong to
 * one user and are kept out of the curated "Available Mock Tests" list.
 */
class AddCustomFlagsToAssessmentsTable extends Migration
{
    public function up()
    {
        Schema::table('assessments', function (Blueprint $table) {
            if (!Schema::hasColumn('assessments', 'is_custom')) {
                $table->boolean('is_custom')->default(0)->index()
                      ->comment('1 = built by a user via the Mock Test Builder');
            }
            if (!Schema::hasColumn('assessments', 'user_id')) {
                $table->integer('user_id')->nullable()->index()
                      ->comment('Owner of a custom test; null for curated tests');
            }
        });
    }

    public function down()
    {
        Schema::table('assessments', function (Blueprint $table) {
            if (Schema::hasColumn('assessments', 'is_custom')) {
                $table->dropColumn('is_custom');
            }
            if (Schema::hasColumn('assessments', 'user_id')) {
                $table->dropColumn('user_id');
            }
        });
    }
}
